name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Generate your awesome content
        uses: ammaraskar/sphinx-action@master
        with:
            build-command: "sphinx-build -b html docs build"

