name: Generate HTML Pages

on:
  push:
    branches:
      - main

jobs:
  sphinx-docs:
    name: Check sphinx docs on Linux
    - name: Install Sphinx dependencies
      run: |
        cd docs
        pip install -r requirements.txt
        sphinx-build -b html . _build
    - name: Create artifact of the html output
      uses: actions/upload-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/_build/
    
    name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}